### ISSUE TITLE
RFE: env var for post build and test command

### ISSUE THREAD

**Issue by jonathanunderwood** [joerick/cibuildwheel#115]
It would be really useful to have a way to specify a command that's run after the wheel build and test operations. The use case I have in mind is uploading a test coverage report to a service such as codecov etc. Currently, one would have to move the generated report to the output directory, and then after cibuildwheel exists, run the upload command, which is all a bit clunky.

**Comment by joerick** [comment]
Hey Jonathan! Thanks for the issue. Have you tried appending your 'copy out' command to the end of the TEST_COMMAND? You can do something like this `CIBW_TEST_COMMAND="test_command && after_successful_test_command"`. Let me know if it works for your use case.

**Comment by jonathanunderwood** [comment]
Hi. Yes, that's what I am doing presently, and it does work. Perhaps my RFE is unecessary for this particular use case, but it felt like something that would be useful. Happy for you to close this if you don't think it's that useful - I also see the value in keeping the codebase as simple as possible.

Thank you for this great tool by the way, I am now using it for the python lz4 bindings. I had previously looked at publishing linux and osx wheels and given up, and then I found your tool :)

**Comment by joerick** [comment]
It wouldn't be too much work to add, but maybe for now we could just use better docs for this kind of use case. The coverage report is something that we don't support very well with our TEST_COMMAND, I must admit.

Does anyone else have experience gathering coverage reports? I'd be curious what our options are - maybe we could build something specific in to CIBW for them.

**Comment by jonathanunderwood** [comment]
Actually, interestingly, that approach *only* works for osx builds. For linux builds, for some reason, `codecov` is unable to recognize the project as a git repo, and coveralls, similarly. See:

https://travis-ci.org/python-lz4/python-lz4/builds/471116521

There's something quite inconsistent between the linux and osx builds.

**Comment by YannickJadoul** [comment]
@jonathanunderwood The reason for this seems to be that the tests are run from a different directory and so you're indeed not in a git repository anymore: see https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/linux.py#L93

I'm not sure on the rationale behind this, but I expect it would be to make sure the installed version is being run rather than the code in the git checkout.

I don't know why it would not give the same problem in macOS, then, because there the command should also be run from `$HOME`? https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/macos.py#L131

**Comment by jonathanunderwood** [comment]
@YannickJadoul yep, I figured that out after posting my comment. I worked around that, and then hit further inconsistencies in how environment variables are passed through to the build: issue #117

**Comment by s-weigand** [comment]
First of all thanks for the awesome tool ❤️ 

Since you were interested in how to gather the coverage reports this is my hacky approach for GitHub-Actions.

The problem with gathering coverage reports (when not directly uploading the form within the docker image) are:
1. You need to get them out of the docker
2. To combine them the paths to the files need to exist on the host

After the actual test command in `CIBW_TEST_COMMAND` is done I run the following script to adjust the paths in the `.coverage` files and make them available at the host.

```python
import sqlite3
import sys
import os
import re


def is_cibuildwheel():
    """Check if run with cibuildwheel."""
    return "CIBUILDWHEEL" in os.environ


def replace_docker_path(path, runner_project_dir):
    """Update path to a file installed in a temp venv to runner_project_dir."""
    pattern = re.compile(r"\/tmp\/.+?\/site-packages")
    return pattern.sub(runner_project_dir, path)


def update_coverag_file(coverage_path, runner_project_dir):
    """
    Since the paths inside of docker vary from the runner paths,
    the paths in the .coverage file need to be adjusted to combine them,
    since 'coverage combine <folder>' checks if the file paths exist.
    """
    try:
        sqliteConnection = sqlite3.connect(coverage_path)
        cursor = sqliteConnection.cursor()
        print("Connected to Coverage SQLite")

        read_file_query = "SELECT id, path from file"
        cursor.execute(read_file_query)

        old_records = cursor.fetchall()
        new_records = [
            (replace_docker_path(path, runner_project_dir), _id) for _id, path in old_records
        ]
        print("Updated coverage file paths:\n", new_records)

        sql_update_query = "Update file set path = ? where id = ?"
        cursor.executemany(sql_update_query, new_records)
        sqliteConnection.commit()
        print("Coverage Updated successfully")
        cursor.close()

    except sqlite3.Error as error:
        print("Failed to coverage: ", error)
    finally:
        if sqliteConnection:
            sqliteConnection.close()
            print("The sqlite connection is closed")


def copy_coverage_cibuildwheel_docker(runner_project_dir):
    """
    When run with cibuildwheel under linux, the tests run in the folder /project
    inside docker and the coverage files need to be copied to the output folder.
    """
    coverage_path = "/project/tests/.coverage"
    if os.path.isfile(coverage_path):
        update_coverag_file(coverage_path, runner_project_dir)
        env_hash = hash((sys.version, os.environ.get("AUDITWHEEL_PLAT", "")))
        os.makedirs("/output", exist_ok=True)
        os.rename(coverage_path, "/output/.coverage.{}".format(env_hash))


if __name__ == "__main__":
    if is_cibuildwheel():
        # for CIBW under linux
        copy_coverage_cibuildwheel_docker("/home/runner/work/<project_name>/<project_name>")
```

Then I combine the files with coverage and upload them with `codecov/codecov-action`.

```yaml
    - name: Set up Python 3.8 to combine coverage Linux
      if: runner.os == 'Linux'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Combine coverage Linux
      if: runner.os == 'Linux'
      run: |
        echo '############ PWD'
        pwd
        python -m pip install coverage[toml]
        echo '############ combine'
        coverage combine ./wheelhouse
        echo '############ XML'
        coverage xml -o ./coverage.xml
        echo '############ FIND'
        find . -name .coverage.*
        find . -name coverage.xml

    - name: Codecov Upload
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
```

I hope someone can point me at a better solution or at least this will help someone with the same struggles.

**Comment by joerick** [comment]
Thank you @s-weigand - your `copy_coverage_cibuildwheel_docker ` and using the `/output` dir is a clever trick! I wonder if we could build in a post test command that supported this better... perhaps the user could do `CIBW_AFTER_TEST=cd {output_dir} && coverage combine --append {package_dir}` and that would aggregate coverage reports in the output folder.

**Comment by s-weigand** [comment]
@joerick Sorry for the late reply.
Since `coverage.py` should now properly support relative paths (https://github.com/nedbat/coveragepy/issues/1147) my `update_coverag_file` hack shouldn't be needed anymore.
As an alternative to using the output folder, one could also mount a different dedicated dir and copy the output there, not to break existing workflows where all files get copied with a plain wildcard `*`.

**Comment by vespakoen** [comment]
I agree there should be an "after-all" / "after-test" command, that can be run inside of the container, I need it to create a tar.gz archive of the compiled Boost.Python libraries, which should be moved into the /host folder once all builds have completed.
The test-command almost works for this purpose, but the problem is that the test-command tries to install the (compiled) python modules, which fails when cross compiling for different architectures.

**Comment by rabyj** [comment]
Yeah I'm having one hell of a hard time just copying my pytest ctrf report out of the container in a consistent way across architectures. I tried to copy to the "output" dir, but this is not allowed in the macOS Github Actions container (`/output: Read-only file system`)

I'm wondering, what's the status on this issue? Are there are any more consistent workarounds, since the latest presented one seems to be Linux only? I haven't found an `after_successful_test_command` that works systematically.

**Comment by joerick** [comment]
@rabyj The `/output` or `/host` trick is only needed on Linux - on macOS/Windows, you can choose to write files anywhere on the filesystem and they'll still be there after the build finishes.

**Comment by rabyj** [comment]
Thanks @joerick, I managed to work out a solution. 

Here's my current setup for reference, if anyone else finds this issue and has trouble making it work:

pyproject.toml:
```toml
[tool.cibuildwheel]
# To test locally, run: cibuildwheel --only cp311-manylinux_x86_64
build = ["cp310-*", "cp311-*", "cp312-*", "cp313-*"]
skip = ["*-musllinux*", "*-manylinux_i686"] # ignore 32-bit Linux builds

test-extras = "test" # installs epigeec[test]

[tool.cibuildwheel.linux]
# ...other stuff...

# Linux-specific: Use /output to persist files from Docker container to host.
test-command = [
    "WHEEL_NAME=$(basename {wheel} .whl)",
    "pytest {project}/epigeec/test --ctrf=\"{project}/reports/ctrf-report-$WHEEL_NAME.json\"",
    "mkdir -p /output/reports && cp -r {project}/reports/* /output/reports/",
]

[tool.cibuildwheel.macos]
# ...other stuff...

# macOS-specific: Write directly to project directory since no container is used.
test-command = [
    "WHEEL_NAME=$(basename {wheel} .whl)",
    "pytest {project}/epigeec/test --ctrf=\"{project}/reports/ctrf-report-$WHEEL_NAME.json\"",
]

[tool.pytest.ini_options]
# Add the project root to the Python path.
# This makes the 'epigeec' package importable.
pythonpath = "."

# Tell pytest where to find tests, which is more explicit.
testpaths = [
    "epigeec/test"
]
```


Workflow files are folded to save space.

<details><summary>.github/workflows/build_wheels.yml</summary>
<p>


```yaml
# .github/workflows/build_wheels.yml
name: Build and Test Wheels

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  push:
    branches:
      - test-publish # Push here for quick build and publish to TestPyPI
      - test-build-full # Push here for full build tests
      - test-build-quick # Push here for quick build tests

# Set default permissions to be read-only for security.
permissions: read-all

jobs:
  # Save PR number for the reporting workflow (report-results.yml)
  prepare:
    name: Prepare PR Information
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      pr_number: ${{ steps.pr_info.outputs.pr_number }}
    steps:
      - name: Save PR Number for reporting workflow
        id: pr_info
        run: |
          echo "${{ github.event.pull_request.number }}" > pr_number.txt
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Upload PR Number Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt

  # Explicitly checks branch names and event types
  # to correctly determine if a full or quick build is needed.
  determine_build_type:
    name: Determine Build Strategy
    runs-on: ubuntu-latest
    outputs:
      full_build: ${{ steps.check.outputs.full_build }}
    # ... [run short script to set full_build output to 'true' or 'false'] ...
  
  # Build wheels for multiple platforms, and test them, uploading results for reporting.
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: determine_build_type
    env:
      CI_MATRIX_OS: ${{ matrix.os }} # Unique identifier for test reporting
    strategy:
      fail-fast: false # Continue building other platforms if one fails
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "x86_64 aarch64"
          - os: macos-13
            cibw_archs: "x86_64"
            deployment_target: "13.0"
          - os: macos-14
            cibw_archs: "arm64"
            deployment_target: "14.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history with tags for setuptools_scm

      - name: Set up QEMU (for ARM on Linux)
      # ... [stuff here] ...

      # Do not set CIBW_BUILD here, let pyproject.toml handle it
      - name: Build wheels (full build)
        if: needs.determine_build_type.outputs.full_build == 'true'
        uses: pypa/cibuildwheel@v3.2.1
        with:
          output-dir: dist
          config-file: pyproject.toml
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target || '' }}

      # Set CIBW_BUILD for quick builds (Python 3.11 only)
      - name: Build wheels (quick build)
        if: |
          needs.determine_build_type.outputs.full_build == 'false' &&
          (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-14')
        uses: pypa/cibuildwheel@v3.2.1
        with:
          output-dir: dist
          config-file: pyproject.toml
        env:
          CIBW_ARCHS: ${{ matrix.os == 'ubuntu-latest' && 'x86_64' || matrix.cibw_archs }}
          CIBW_BUILD: cp311-*
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target || '' }}

      # Create a sanitized string for the artifact name
      # Since we can't use a 'replace' function directly in the upload-artifact name field
      - name: Generate artifact name
        id: artifact_name
        shell: bash
        run: |
          archs="${{ matrix.cibw_archs }}"
          echo "arch_string=${archs// /-}" >> $GITHUB_OUTPUT

      # Upload built wheels
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        if: "!env.ACT"
        with:
          name: wheels-${{ matrix.os }}-${{ steps.artifact_name.outputs.arch_string }}
          path: dist/*.whl
          if-no-files-found: ignore  # Don't fail if no wheels were built

      # Upload test results.
      # cibuildwheel writes tests to `reports` directory, this grabs all reports.
      - name: Upload Test Report Artifact
        if: "!env.ACT"
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ steps.artifact_name.outputs.arch_string }}
          # Look for reports in both possible locations
          path: |
            reports/
            dist/reports/
          if-no-files-found: ignore  # Don't fail if no reports were generated

  # [then other jobs follow, such as building from source and publishing to PyPI] ...
```

</p>
</details>


<details><summary>.github/workflows/report-results.yml</summary>
<p>

```yaml
# .github/workflows/report-results.yml
name: Report Test Results
on:
  workflow_run:
    workflows: ["Build and Test Wheels"] # Match the 'name:' of the first workflow
    types:
      - completed
  workflow_dispatch:  # Manual trigger for testing
    inputs:
      run_id:
        description: 'Workflow run ID from build_wheels.yml'
        required: true
        type: string

jobs:
  report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    # Only run for pull requests, or allow manual dispatch
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.event == 'pull_request'

    permissions:
      pull-requests: write

    steps:
      # Set the run_id to use based on trigger type
      - name: Determine run ID
        id: run_id
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "id=${{ inputs.run_id }}" >> $GITHUB_OUTPUT
          else
            echo "id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          fi
      # Download PR number artifact created by main workflow
      - name: Download PR Number artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: pr_number
          run_id: ${{ steps.run_id.outputs.id }}

      - name: Read PR number from file
        id: pr_number
        run: echo "number=$(cat pr_number.txt)" >> $GITHUB_OUTPUT

      # Download all test result artifacts
      - name: Download all test result artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          name: test-results-*
          name_is_regexp: true
          merge_multiple: true
          run_id: ${{ steps.run_id.outputs.id }}
          path: all-test-results

      # Get all reports and publish them using ctrf-io/github-test-reporter
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'all-test-results/**/*.json'
          pull-request: true
          update-comment: true
          comment-tag: '${{ github.workflow }}-${{ github.job }}'
          issue: ${{ steps.pr_number.outputs.number }}
        if: always()
```

</p>
</details>
