### ISSUE TITLE
Windows support in Travis CI

### ISSUE THREAD

**Issue by cher-nov** [joerick/cibuildwheel#144]
FYI
https://blog.travis-ci.com/2018-10-11-windows-early-release
https://travis-ci.community/t/python-support-on-windows/241

And yes, your project is simply amazing, keep up the good work!

**Comment by hannesmuehleisen** [comment]
FWIW, I managed to get `cibuildwheel` to work on Windows Travis, here the relevant snippet of my `.travis.yml`

````yaml
language: cpp

before_install:
  - eval "${MATRIX_EVAL}"

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.16" && pip install "pandas>=0.24" && pip install "pytest>=4.3" && pip install cmake==3.13.3'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'

matrix:
  include:

    - os: windows
      name: Python Package
      language: cpp
      filter_secrets: false

      before_install:
        - choco install python3 --version 3.7.3 --sidebyside -y --forcex86 --force --params "/InstallDir:C:\Python37"
        - choco install python3 --version 3.7.3 --sidebyside -y --force --params "/InstallDir:C:\Python37-x64"

        - C:/Python37-x64/python.exe -m pip install --upgrade pip
        - C:/Python37-x64/python.exe -m pip install "cibuildwheel==0.10.2"

      script:
        - cd tools/pythonpkg
        - C:/Python37-x64/python.exe  setup.py sdist
        - mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        - C:/Python37-x64/python.exe -m cibuildwheel --platform windows --output-dir wheelhouse duckdb_tarball
        - cd ../..
````
