### ISSUE TITLE
Interaction with Travis stages

### ISSUE THREAD

**Issue by MaxHalford** [joerick/cibuildwheel#190]
Hey,

Sorry for the silly question, but I'm struggling with seeing how to build wheels for multiple platforms when using Travis stages. I'm aware of [this example](https://github.com/YannickJadoul/Parselmouth/blob/515b635fb50a9161e0d58944a9feee691a2ddf9b/.travis.yml#L80-L173) by @YannickJadoul, but I'm not well-versed enough in Travis to understand what's going on.

AFAIK, stages are the recommended way to use Travis. However, by looking at their documentation [it seems](https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix) that setting the `matrix` field is orthogonal to the `stages` field. The issue is that the "Travis CI" example in the README of `cibuildwheel` uses the `matrix` field.

On a sidenote, the `.travis.yml` file I'm working on is [here](https://github.com/creme-ml/creme/blob/master/.travis.yml). For the while it only builds wheels for `manylinux i686` and `manylinux x86_64` (even though MacOS is added to the `matrix` field). Ideally I would like to also build wheels for MacOS and Windows, if possible in a smooth way.

Hopefully I'm not the only one struggling with this!

**Comment by YannickJadoul** [comment]
@MaxHalford Stages are still in beta, though, or not anymore?  

> AFAIK, stages are the recommended way to use Travis.

You don't per se need them, as far as I understand. They're mainly meant as a level of grouping multiple single jobs within a full configuration. And the advantage is that if a job fails in one of the stages, later stages won't be built.

But yes, the integration with `matrix` is not always perfect. I recently had an issue where the global `env` was somehow not used in one of the stages...
Actually, in your case, the problem is that `matrix:` and `jobs: include:` are orthogonal. `jobs: include:` (or `jobs: exclude:`) tweak the jobs created by the combinatorial matrix expansion. (As you can see in the example you link to, I don't even use the `matrix` expansion, but just manually list all the different jobs that need to be run.)

I think the easiest you can do is to repeat this block three times:

```yaml
  - stage: pypi
    sudo: required
    services:
      - docker
    env:
      - CIBW_BUILD="cp36-* cp37-*"
      - CIBW_BEFORE_BUILD="pip install cython"
    install:
      - pip install cibuildwheel==0.12.0 cython twine
    script:
      - cibuildwheel --output-dir dist
      - python setup.py sdist
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present

  - stage: pypi
    os: osx
    language: generic
    env:
      - CIBW_BUILD="cp36-* cp37-*"
      - CIBW_BEFORE_BUILD="pip install cython"
    install:
      - pip install cibuildwheel==0.12.0 cython twine
    script:
      - cibuildwheel --output-dir dist
      - python setup.py sdist
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present

  - stage: pypi
    os: windows
    language: shell
    env:
      - CIBW_BUILD="cp36-* cp37-*"
      - CIBW_BEFORE_BUILD="pip install cython"
    install:
      - pip install cibuildwheel==0.12.0 cython twine
    script:
      - cibuildwheel --output-dir dist
      - python setup.py sdist
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present
```

You can stop repeating yourself too much by doing something like this, though, using YAML's `&` and `*` to repeat values:

```yaml
  - stage: pypi
    sudo: required
    services:
      - docker
    env: &pypi-env
      - CIBW_BUILD="cp36-* cp37-*"
      - CIBW_BEFORE_BUILD="pip install cython"
    install: &pypi-install
      - pip install cibuildwheel==0.12.0 cython twine
    script: &pypi-script
      - cibuildwheel --output-dir dist
      - python setup.py sdist
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present

  - stage: pypi
    os: osx
    language: generic
    env: *pypi-env
    install: *pypi-install
    script: *pypi-script
    if: tag IS present

  - stage: pypi
    os: windows
    language: shell
    env: *pypi-env
    install: *pypi-install
    script: *pypi-script
    if: tag IS present
```
