### ISSUE TITLE
python 3.8 build problem

### ISSUE THREAD

**Issue by MuellerSeb** [joerick/cibuildwheel#195]
Hey there,

I use ``cibuildwheel`` to build wheels of a small python package including some cython routines called [pentapy](https://github.com/GeoStat-Framework/pentapy).

I now tried to also build wheels for python 3.8 using cibuildwheel from this [commit](https://github.com/joerick/cibuildwheel/commit/3c9875db19dae7480a833ab44304c4ba7aea9fcf), using the follwing script for TravisCI (matrix shortened, full script [here](https://github.com/GeoStat-Framework/pentapy/blob/py35-py38/.travis.yml)):

```yml
language: python

matrix:
  include:
    # xenial: https://github.com/travis-ci/travis-ci/issues/9815
    - name: "Linux py37"
      sudo: required
      language: python
      python: 3.7
      dist: xenial
      services: docker
      env: CIBW_BUILD="cp37-*"

    - name: "Linux py38"
      sudo: required
      language: python
      python: 3.8
      dist: xenial
      services: docker
      env:
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.3 cython==0.29.14 setuptools"
        - CIBW_BUILD="cp38-*"

    - name: "MacOS py38"
      os: osx
      language: generic
      env:
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.3 cython==0.29.14 setuptools"
        - CIBW_BUILD="cp38-*"

    - name: "Win py38"
      os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.8 --no-progress -y
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.3 cython==0.29.14 setuptools"
        - CIBW_BUILD="cp38-*"
env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install numpy==1.14.5 cython==0.28.3 setuptools"
    - CIBW_TEST_REQUIRES=pytest
    # no "__init__.py" in tests/ to run tests against installed wheel
    # https://doc.pytest.org/en/3.0.4/goodpractices.html#choosing-a-test-layout-import-rules
    - CIBW_TEST_COMMAND="python -m pytest -v {project}/tests"

script:
  # create wheels
  # - python -m pip install cibuildwheel==0.13.0
  - python -m pip install https://github.com/joerick/cibuildwheel/archive/3c9875db19dae7480a833ab44304c4ba7aea9fcf.zip
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # pypi upload ("test.pypi" allways and "pypi" on TAG)
  - python -m pip install twine
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload --verbose --skip-existing wheelhouse/*
    fi
notifications:
  email:
    recipients:
    - info@geostat-framework.org
```
The problem now is, that all py<38 versions succeed and build wheels perfectly but all py38 builds succeed false positively with no wheels build.
See here: https://test.pypi.org/project/pentapy/1.1.0.dev0/#files

For example, for macOS py38, cibuildwheel shows the following:

```bash
$ python -m cibuildwheel --output-dir wheelhouse
     _ _       _ _   _       _           _
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|
cibuildwheel version 0.12.0
Build options:
  platform: 'macos'
  before_build: 'pip install numpy==1.17.3 cython==0.29.14 setuptools'
  build_selector: BuildSelector('cp38-*' - '')
  build_verbosity: 0
  environment: ParsedEnvironment([])
  output_dir: 'wheelhouse'
  project_dir: '.'
  test_command: 'python -m pytest -v {project}/tests'
  test_extras: ''
  test_requires: ['pytest']
Here we go!
+ curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1734k  100 1734k    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 12.9M
The command "python -m cibuildwheel --output-dir wheelhouse" exited with 0.
```

Almost the same for linux and windows.
Full output here: https://travis-ci.org/GeoStat-Framework/pentapy/builds/609321050

Do you have any idea, what went wrong?

Thanks for you help in advance!
Sebastian
