### ISSUE TITLE
Consider including a link to Azure templates

### ISSUE THREAD

**Issue by astrofrog** [joerick/cibuildwheel#229]
Building on top of cibuildwheel, @Cadair and I have developed an Azure template that makes it very easy for developers to add wheel and sdist building to their repositories:

https://github.com/OpenAstronomy/azure-pipelines-templates/

With this template, the Azure configuration can look as simple as:

```
jobs:
- template: publish.yml@OpenAstronomy
  parameters:
    pypi_connection_name: 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macos
    - wheels_windows
```

But still allows the ``CIBW`` env variables to be set if needed. I thought it might be worth linking to this from the README here? (but feel free to close if not)
