### ISSUE TITLE
python not found on windows

### ISSUE THREAD

**Issue by louisabraham** [joerick/cibuildwheel#285]
Hi, I think one has to specify the path to Python on Travis.

I could get the code to work with:

```yaml
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      install:
       - /c/Python38/python.exe -m pip install cibuildwheel
      script:
        - /c/Python38/python.exe -m cibuildwheel --output-dir wheelhouse
```

I guess the export is not necessary.

**Comment by louisabraham** [comment]
related to https://github.com/joerick/cibuildwheel/issues/288#issuecomment-595323063

**Comment by joerick** [comment]
You should install modules inside CIBW_BEFORE_BUILD, so it installs into each environment separately.

The problem above is perhaps because we just updated the examples to use `python3` instead of `python` - I'm guessing Windows doesn't follow those conventions.

**Comment by joerick** [comment]
Yes, that appears to be the case.

```yaml
language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        # install Python 3 and make sure it's on PATH as 'python3'
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe  # <- added

install:
  - python3 -m pip install cibuildwheel==1.0.0

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
```

@YannickJadoul can you think of a cleaner way to do this? We want to ensure that python3 is run on macOS/Linux, but Windows installs of Python only have it available as `python`.

I can update the examples with the above, but it is a _little_ hacky...
