### ISSUE TITLE
Support for drone.io

### ISSUE THREAD

**Issue by ShadowJonathan** [joerick/cibuildwheel#340]
Could drone.io be supported?

Drone.io is an open-source selfhosted/cloud CI, I expected an issue/request to be here regarding it, but I found none, so I'm opening one now.

Drone.io provides a versatile build environment on custom or cloud runners, not unlike selfhosted Github Actions runners. But my personal setup consists of linux-docker-based runners.

**Comment by joerick** [comment]
Could well be possible. The Linux build calls `docker` as a subprocess to perform the build. Can Drone.io Docker runners get access to a Docker daemon somehow?

**Comment by ShadowJonathan** [comment]
https://docs.drone.io/pipeline/docker/examples/services/docker_dind/

Yes, that's possible.

**Comment by joerick** [comment]
Cool - it's possible we wouldn't have to modify cibuildwheel at all to make this work - it should detect a CI environment using the `CI` env var that's set by Drone. Start with that `docker_dind` example, and call cibuildwheel with something like `cibuildwheel --output-dir wheelhouse .`. It might just work! If so, I'd be happy to add it to the docs.

**Comment by ShadowJonathan** [comment]
Alrighty, i'll probably make work of this issue and make a pull request later on, but i'll keep this issue like this in case i forget or someone else wants to pick it up 👍

**Comment by ShadowJonathan** [comment]
Planning to work on this later today, have a bit of reference documentation that im gonna use: https://docs.drone.io/pipeline/environment/reference/

**Comment by ShadowJonathan** [comment]
im afraid i cant support windows with this CI, there's too much messing around with container images and pre-flight-check installations to *try* to make it work, i've kinda given up after trying this config with these results:

<details>
 <summary>Config</summary>

```yml
steps:
  - name: Test
    #python:3.8-windowsservercore-1809
    image: stefanscherer/chocolatey
    commands:
      - choco install visualstudio2017buildtools -y
      - choco install python3 --version 3.8.3 --no-progress -y
      # - choco install vcpython27 -f -y
      - py -m pip install -r requirements-dev.txt
      - py -u ./bin/run_tests.py
    environment:
      CIBW_BUILD: cp3?-*
```

</details>

<details>
 <summary>Results</summary>

```
[Test:169] Chocolatey installed 9/9 packages.
[Test:170]  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[Test:171]
[Test:172] Installed:
[Test:173]  - visualstudio2017buildtools v15.9.23.0
[Test:174]  - kb2919355 v1.0.20160915
[Test:175]  - kb2999226 v1.0.20181019
[Test:176]  - dotnetfx v4.8.0.20190930
[Test:177]  - chocolatey-visualstudio.extension v1.8.1
[Test:178]  - kb2919442 v1.0.20160915
[Test:179]  - visualstudio-installer v2.0.1
[Test:180]  - chocolatey-dotnetfx.extension v1.0.1
[Test:181]  - chocolatey-windowsupdate.extension v1.0.4
[Test:182]
[Test:183] Packages requiring reboot:
[Test:184]  - dotnetfx (exit code 3010)
[Test:185]
[Test:186] The recent package changes indicate a reboot is necessary.
[Test:187]  Please reboot at your earliest convenience.
2020/05/26 12:53:02 Test : exit code 3010
```

</details>

Which ultimately means there has to be a windows container image that has:
- Chocolatey
- Build Tools 2017
- dotnet3.5 installed/supported (I couldn't get this installed through chocolatey, and `vcpython27` requires it)

Which I haven't found yet.

@joerick would it be alright to (not yet) support windows through drone.io if/when I make a PR to add support for Drone? I can probably make an open-standing issue for it if there's really that much interest for it.
