### ISSUE TITLE
Generated wheels are not manylinux compatible

### ISSUE THREAD

**Issue by mwilliamson** [joerick/cibuildwheel#343]
I've tried using cibuildwheel to build manylinux wheels, but users are reporting that the wheels aren't manylinux compatible: trying to import results in the error:

```
ImportError: /usr/local/lib/python3.5/dist-packages/jq.cpython-35m-x86_64-linux-gnu.so: symbol scalbln, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
```

I don't suppose you'd have any idea what's gone wrong?

User reports: https://github.com/mwilliamson/jq.py/issues/43

Travis configuration used to build the wheels: https://github.com/mwilliamson/jq.py/blob/master/.travis.yml

Travis job that built the wheels: https://travis-ci.org/github/mwilliamson/jq.py/jobs/682250868

Apologies if this is totally the wrong place to ask -- please feel free to point me in a different direction.

**Comment by YannickJadoul** [comment]
Hmmm, that's quite worrying. I'm looking at your project and into what could cause the problem, but meanwhile: do you link any external dependencies? Are any of these compiled outside of `cibuildwheel` (and thus outside of the docker image) ?

**Comment by mwilliamson** [comment]
The project depends on jq and oniguruma. They're built within setup.py, so I'd assume that they're built within the docker image.

**Comment by YannickJadoul** [comment]
Ah, yes, I hadn't checked that. And you're not installing any newer compiler or something like that?

So there are two weird things happening, then: 1) inside a manylinux image, non-compatible things are built, and 2) auditwheel approves these wheels.

**Comment by mwilliamson** [comment]
> Ah, yes, I hadn't checked that. And you're not installing any newer compiler or something like that?

I don't think so! This is the job for the Linux wheels:

```
jobs:
  include:
    - if: tag =~ /^([0-9]+\.[0-9]+\.[0-9]+)(\.?(dev|a|b|rc)[0-9]+)?$/
      name: "Linux wheels"
      services:
        - "docker"
      python: "3.8"
      install:
        - python3 -m pip install cibuildwheel==1.3.0 twine virtualenv
      script:
        - export CIBW_BEFORE_BUILD="pip install cython==0.29.16 && cython {project}/jq.pyx"
        - export CIBW_TEST_REQUIRES="-r test-requirements.txt"
        - export CIBW_TEST_COMMAND="nosetests {project}/tests"
        - python3 -m cibuildwheel --output-dir wheelhouse &&
          twine check wheelhouse/*.whl &&
          twine upload wheelhouse/*.whl --skip-existing
```
