### ISSUE TITLE
For GH Actions, use gh-action-pypi-publish instead of twine

### ISSUE THREAD

**Issue by breznak** [joerick/cibuildwheel#361]
There are some "problems"/tricks described when using `twine` with this action. 
Use dedicated GH action instead? 

```
- name: Publish to PyPI
  uses: pypa/gh-action-pypi-publish@master
  with:
    user: __token__
    password: ${{ secrets.pypi_password }}
    repository_url: https://test.pypi.org/legacy/ #TODO rm for real pypi
    packages_dir: ./wheelhouse/
```

**Comment by joerick** [comment]
:+1: - good idea. If you have time, adding an example config to the `/examples` dir would be nice :)

**Comment by YannickJadoul** [comment]
Closing this for now, as https://github.com/pypa/gh-action-pypi-publish is only supported on Linux :-(

**Comment by henryiii** [comment]
I believe this is how you upload:

https://scikit-hep.org/developer/gha_wheels#publishing

(Will be tested on the next release of boost-histogram)

You just need a upload artifacts (useful anyway for checking the results if you haven't published yet), it makes sure you have no errors in any of the builds (no partial uploads), and is a good place to make the sdist. I don't think there's much to be gained in making the upload action multi platform or adding the ability to skip existing; this is a good workflow.

Also see setuptools_scm for a nice example of an upload. Be sure to use v2 of upload and download actions.

**Comment by breznak** [comment]
In the past I had no luck with gha, this action works flawlessly for me
```
- name: GitHub Release C++ (deploy)
  if: (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags'))
  uses: softprops/action-gh-release@v1
  with:
    files: |
      dist/htm_core-v*
      dist/*.whl
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
