### ISSUE TITLE
Windows pyproject.toml cannot handle versioned dependencies

### ISSUE THREAD

**Issue by jbarlow83** [joerick/cibuildwheel#392]
If pyproject.toml specifies a versioned dependency, such as...

```toml
[build-system]
requires = [
  "setuptools >= 30.3.0",
]
build-backend = "setuptools.build_meta"
```

then in windows.py, the code current parses the requirements and calls...

```python
return subprocess.check_call(' '.join(args), env=env, cwd=cwd, shell=True)
```

which means that the result of `' '.join(args)` is...

```
pip install setuptools >= 30.3.0
```

which breaks the shell parser since that needs to be quoted to be not be a redirect.

`shell=True` is usually bad mojo. It should work to do `subprocess.check_call(args, env=env, cwd=cwd)`.
