### ISSUE TITLE
Access host from CIBW_TEST_COMMAND

### ISSUE THREAD

**Issue by kavvkon** [joerick/cibuildwheel#52]
Is it possible to access the folders of the cloned repository from the CIBW_TEST_COMMAND ?
I run the cibuildwheels in a subfolder, so some scripts in the root are not accessible in the container.

Could {host} work similar to {project} ?

**Comment by YannickJadoul** [comment]
The root of the system is available as `/` on Windows and OS X (since we're on the same system), and the root of the host running the Docker image as `/host` on Linux builds.

If this does not solve your problem, could you give an example of the use case?

**Comment by kavvkon** [comment]
In the README you mention:

> Environment variable: CIBW_TEST_COMMAND
> --
> Shell command to run tests after the build. The wheel will be installed automatically and available for import from the tests. The project root should be included in the command as "{project}".
> 
> Example: nosetests {project}/tests

If we run cibuildwheels on a subfolder how can we access the root of our cloned repository (e.g. for travis $TRAVIS_BUILD_DIR) from the CIBW_TEST_COMMAND?  Something like {home} or {host} ...

More specifically I want to access something during pytests that is downloaded from the travis script in the home folder and has to be used in all tests in a consistent way in mac,linux and appveyor ...
e.g.: https://travis-ci.org/kavvkon/gams-api/jobs/329083740

**Comment by YannickJadoul** [comment]
There's not really anything like that since (as far as I can see) `cibuildwheel` doest not really know about this. You only start `cibuildwheel` from a certain directory, and the git clone directory that Travis CI/AppVeyor downloads your project into is on a higher level than `cibuildwheel`.

Couldn't you move/copy/link your file before starting `cibuildwheel`?

If not, you could quickly write an if statement on the OS in the CI configurations: Windows/AppVeyor -> `%APPVEYOR_BUILD_FOLDER%`, OS X/Travis CI -> `"$TRAVIS_BUILD_DIR"`, and Linux/Travis CI -> `"/host$TRAVIS_BUILD_DIR"` (since this one is running in a docker image!)

**Comment by joerick** [comment]
As @YannickJadoul mentioned, this is not possible in the Docker due to the way the filesystems are mounted.

The `/host` mountpoint should provide the escape hatch for you, though... something like `CIBW_ENVIRONMENT="repo_root=/host/project"` on Travis should allow you to get back to dry land.

**Comment by kavvkon** [comment]
Hey.. Sorry for reopening this but still did not manage to make it work

I try to define as you suggest but it seems that it is not parsed properly:

`environment: ParsedEnvironment(['GAMS_DIR=/host$TRAVIS_BUILD_DIR/gams'])`
so when I check from the container it has the value: 'GAMS_DIR': '/host/gams',

Here is the config file
https://travis-ci.org/kavvkon/gams-api/jobs/445038025/config

**Comment by YannickJadoul** [comment]
No problem. Thanks for reopening.

But why is that not parsed properly? If I see `'GAMS_DIR=/host${TRAVIS_BUILD_DIR}/gams'` in your `.travis.yml` and you are showing `GAMS_DIR=/host$TRAVIS_BUILD_DIR/gams`, so something has happened to that environment.

Could it rather be that the problem is that `TRAVIS_BUILD_DIR` is not defined inside the `manylinux1` container?

**Comment by kavvkon** [comment]
Wouldn't it be better to replace the `'$TRAVIS_BUILD_DIR'` with its value while parsing it ? 
In that case you don't have to define it in the container

I havent tested yet but I guess the same should apply for mac and windows

**Comment by YannickJadoul** [comment]
In this case, that would work, but I believe there's other cases where this would be a problem (e.g. when the result of an environment variable comes from the execution of a command to get the architecture).

I do agree that accessing the host's environment variables seems like a logical thing to do.

**Comment by kavvkon** [comment]
Well I am not sure as the file is downloaded at the $HOME of Travis.
I have 3 projects in the repository:

**Directory structure**

TRAVIS_BUILD_DIR
|-GAMS_DIR (big library that I need for the tests in each project)
|- proj1 (projects to build with cibuildwheel)
|- proj2
|- proj3

**Travis script**
```
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2


env:
  global:
    - CIBW_SKIP='cp35-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_TEST_COMMAND='pytest -v {project}/tests/'
    - CIBW_ENVIRONMENT='GAMS_DIR=/host$TRAVIS_BUILD_DIR/gams'
    - GAMS=24.9
    - GAMS_URL=https://d37drm4t2jghv5.cloudfront.net/xxx.zip

install:
  # Install GAMS
  - wget -N $GAMS_URL -O gams.zip
  - unzip -qu gams.zip -d $HOME
  - ln -s $HOME/gams${GAMS}_linux_x64_64_sfx ${TRAVIS_BUILD_DIR}/gams #ln to root
  - export PATH="$HOME/gams:$PATH"


script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel ./proj1--output-dir wheelhouse
  - cibuildwheel ./proj2--output-dir wheelhouse
  - cibuildwheel ./proj3 --output-dir wheelhouse

```
