### ISSUE TITLE
how to disable manylinux1

### ISSUE THREAD

**Issue by xiispace** [joerick/cibuildwheel#522]
after ci build, there are lots of whl files
```
hvloop-0.0.2-cp36-cp36m-manylinux1_x86_64.whl 
hvloop-0.0.2-cp36-cp36m-manylinux2010_x86_64.whl
hvloop-0.0.2-cp37-cp37m-manylinux1_x86_64.whl
hvloop-0.0.2-cp37-cp37m-manylinux2010_x86_64.whl
```
i only want the *manylinux2010* files, is there some way to disabled the manylinux1 files build

below is my github action build.yml
```
name: Build and upload to PyPI

on: [push,]

jobs:
  build_wheels:
    name: Build whells on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - uses: actions/setup-python@v2
        with:
            python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp3?-*
          CIBW_SKIP: "*-win32 *-manylinux_i686 cp35-*"
          CIBW_BEFORE_BUILD: "pip install -U cython cmake"

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```
