### ISSUE TITLE
Idea: Capture build dependencies for complicated wheels in pyproject.toml

### ISSUE THREAD

**Issue by chrisantonellis** [joerick/cibuildwheel#564]
Hello! I'm looking for feedback on the following idea. I'd be happy to make a contribution to this project

When a python package doesn't provide a manylinux wheel on PyPI when it could, what do you do? Build it yourself. Or what if you want the package linked against a different version of a system library? Build it yourself.

This becomes expensive when operating at scale, building and hosting internally compiled python packages for large organizations is a bummer. In part because the "recipes" for building complicated wheels are only captured in project and platform specific documentation. I'm looking at you pandas.

What if the data required to modify a build environment was captured in "steps" similar to the CI configurations used by this tool? Set environment variables, install `system_deps-1.0.0`, install `python_deps==1.0.0`, run bash steps etc.

With this info captured as part of `pyproject.toml` it would be versioned, and could be contributed to by consumers of the package.

```toml
[manylinux_build_specification.manylinux2014]
extra_base_system_repositories = ["http://foo.com/packages/"]
system_dependencies = ["foo-1.0.0", "bar-1.0.0"]
python_dependencies = ["foo==1.0.0", "bar==1.0.0"]
environment_variables = ["FOO=BAR"]
steps = [
  "./scripts/build_and_upload.sh --my_option"
]
```

thanks for any and all input!
