### ISSUE TITLE
Tiny feat: Add printout of produced wheels at end of logs

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#566]
One thing I have in common for all my uses of cibuildwheel is:

```yaml
    - uses: joerick/cibuildwheel@v1.8.0

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash
```

It might be a nice to list the built wheel names at the end of the logs, so it's easy to tell what's been produced. (If actions/upload-artifact printed the name of the files it was uploading, this wouldn't be so important, but it doesn't)
