### ISSUE TITLE
How to not build manylinux1 build? 

### ISSUE THREAD

**Issue by animalize** [joerick/cibuildwheel#600]
If use these options:
```yaml
    env:
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      CIBW_ARCHS_LINUX: "auto aarch64"
```
`cibuildwheel` builds these wheels:
```
pyzstd-0.14.1-cp39-cp39-manylinux1_i686.whl
pyzstd-0.14.1-cp39-cp39-manylinux2014_aarch64.whl
pyzstd-0.14.1-cp39-cp39-manylinux2014_i686.whl
pyzstd-0.14.1-cp39-cp39-manylinux2014_x86_64.whl
```
I want to not build `manylinux1` build, if add this line:
```
CIBW_SKIP: "*manylinux1_i686*"
```
Then `manylinux2014_i686.whl` build is not built as well:
```
pyzstd-0.14.1-cp39-cp39-manylinux2014_aarch64.whl
pyzstd-0.14.1-cp39-cp39-manylinux2014_x86_64.whl
```
