### ISSUE TITLE
Building wheels for manylinux aarch64 got stuck at downloading the image

### ISSUE THREAD

**Issue by xuyxu** [joerick/cibuildwheel#612]
Hi, thanks for this great repo. We are currently using this package to build wheels for manylinux aarch64.

However, the building process got stuck at downloading the image on our GitHub Action CI Server.

```
Unable to find image 'quay.io/pypa/manylinux2014_aarch64:2021-01-24-91ce2b8' locally
  2021-01-24-91ce2b8: Pulling from pypa/manylinux2014_aarch64
  6717b8ec66cd: Pulling fs layer
  adea6a3814c2: Pulling fs layer
  db611ba5718b: Pulling fs layer
  c06460ee9f3a: Pulling fs layer
  5fcb4101e8d8: Pulling fs layer
  a9955bdb0bcf: Pulling fs layer
  c06460ee9f3a: Waiting
  5fcb4101e8d8: Waiting
  a9955bdb0bcf: Waiting
  db611ba5718b: Verifying Checksum
  db611ba5718b: Download complete
  adea6a3814c2: Verifying Checksum
  adea6a3814c2: Download complete
  c06460ee9f3a: Verifying Checksum
  c06460ee9f3a: Download complete
  5fcb4101e8d8: Download complete
  6717b8ec66cd: Verifying Checksum
  6717b8ec66cd: Download complete
  a9955bdb0bcf: Verifying Checksum
  a9955bdb0bcf: Download complete
  6717b8ec66cd: Pull complete
  adea6a3814c2: Pull complete
  db611ba5718b: Pull complete
  c06460ee9f3a: Pull complete
  5fcb4101e8d8: Pull complete
  a9955bdb0bcf: Pull complete
  Digest: sha256:e4e122eb0dde2a6a96e3344e32e4dec2bd3b5097e93c117216b5bb273a04753b
  Status: Downloaded newer image for quay.io/pypa/manylinux2014_aarch64:2021-01-24-91ce2b8
  WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

Full running logs are available [here](https://github.com/LAMDA-NJU/Deep-Forest/pull/47/checks?check_run_id=2012420827), and the config file is displayed below:

``` bash
name: Build-Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_BUILD: "cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp36-win_amd64 cp37-win_amd64 cp38-win_amd64 cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64 cp36-manylinux_aarch64 cp37-manylinux_aarch64 cp38-manylinux_aarch64"
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```

I will much appreciate your help, thanks!

**Comment by henryiii** [comment]
You need to enable emulation, something like:

```yaml
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
```

See https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation

**Comment by Czaki** [comment]
This image pulled correctly. The error happens when docker command was run. 

The real error is here:
```
      + /bin/true
  standard_init_linux.go:219: exec user process caused: exec format error
  Error: The operation was canceled.
```

But I do not understand why its happens. 


Additional. Why You have python version in matrix? `cibuildwheel` install needed python version itself. it needs only single python executable per system.  You could simplify it to: 

```
name: Build-Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_BUILD: "cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp36-win_amd64 cp37-win_amd64 cp38-win_amd64 cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64 cp36-manylinux_aarch64 cp37-manylinux_aarch64 cp38-manylinux_aarch64"
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```
