### ISSUE TITLE
OSX build fails (TLS version error)

### ISSUE THREAD

**Issue by TheBB** [joerick/cibuildwheel#63]
Hi,

I tried following the instructions [here](https://github.com/joerick/cibuildwheel#minimal-setup), which work fine for Linux, but seem to fail on OSX. Example: https://travis-ci.org/sintefmath/Splipy/jobs/370590848

This seems related to https://github.com/joerick/cibuildwheel/pull/57 which claims to be fixed, so I am sure I'm just doing something wrong here.

.travis.yml file is

```yaml
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_SKIP="cp27-* cp33-*"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_SKIP="cp27-* cp33-*"

script:
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
```
