### ISSUE TITLE
Python3 - NumPy - MacOs workflow problem

### ISSUE THREAD

**Issue by SantoSimone** [joerick/cibuildwheel#637]
Hi everyone, I have a private repo on which I am trying to start a workflow.
After #632, I have tried to port the approach used in a simple repo to this new one, but I am facing a new error:
```
  Building wheels for collected packages: cv-exp
    Building wheel for cv-exp (setup.py): started
    Building wheel for cv-exp (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /private/tmp/cibw_bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-1dhgvd48/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-1dhgvd48/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-wheel-n6jx47h3
         cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-1dhgvd48/
    Complete output (59 lines):
    running bdist_wheel
    running build
    running build_ext
    -- The C compiler identification is AppleClang 12.0.0.12000032
    -- The CXX compiler identification is AppleClang 12.0.0.12000032
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Searching for Python3
    CMake Error at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found
      version "3.9.2")
    Call Stack (most recent call first):
      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/FindPython/Support.cmake:2984 (find_package_handle_standard_args)
      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
      CMakeLists.txt:13 (find_package)
```

This (should) mean that NumPy cannot be found, but I explicitly installed it before building the wheel. For full reference i leave a snippet of my files.

```
#.yml file

name: cibuildwheel test

on: 
  push: 
    branches:
      - feature/ipd3.0*
      
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # probably this is useless
      - name: Change directory
        run: |
          cd my/path/
          
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        # to supply options, put them in 'env', like:
        with:
          package-dir: ./my/path
          output-dir: wheelhouse
        env:
          CIBW_BUILD: cp39-*
          CIBW_VERBOSITY: 3
          CIBW_BEFORE_BUILD: pip install -r my/path/requirements.txt
          CIBW_SKIP: pp* 

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```

```
# requirements.txt

numpy
wheel
cmake
```

```
# CMakeLists.txt

cmake_minimum_required(VERSION 3.16)
#set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_DEBUG_TARGET_PROPERTIES INCLUDE_DIRECTORIES)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

project(cv_exp_cpp)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

message(STATUS "Searching for Python3")

# This is the crashing line
find_package(Python3 COMPONENTS Interpreter Development NumPy REQUIRED)
```

I have also tried to fix version of numpy to 1.18.5, but it did not help.
Any thoughts on this?

Btw, thanks for this great work!
